#!/usr/bin/env python
#         --Common SConscripts--
# Things below here will be shared between libtide and
# any parent builds (ie Tide) -- so basically no
# libtide-specific stuff below here
import os.path as path
Import('build')
Import('debug')

SConscript('boot/SConscript', variant_dir=path.join(build.dir, 'objs', 'boot'), duplicate=0)
SConscript('libtide/SConscript', variant_dir=path.join(build.dir,'objs','libtide'), duplicate=0)

# Now that libtide is built add it as a default for
# all the following build steps. This means that things
# that should not depend on libtide should be built
# before here.
build.env.Append(LIBS=['tide'])
build.env.Append(LIBPATH=[build.runtime_build_dir])

SConscript('modules/SConscript')
